# Generated by Django 2.2 on 2021-03-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=125, verbose_name='Email Address')),
                ('full_name', models.TextField(max_length=125, verbose_name='Full Name')),
                ('score', models.IntegerField(default=1, verbose_name='Score')),
            ],
        ),
    ]
